---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

## Overview

JAMES is a web service for creating and interpreting charts of child growth and development. The current version

1. provides access to high-quality growth charts used by the Dutch youth health care;
2. interchanges data coded according to the [Basisdataset JGZ](https://decor.nictiz.nl/pub/jeugdgezondheidszorg/jgz-html-20240426T081156/index.html);
3. screens for abnormal height, weight and head circumference;
4. converts developmental data into the D-score;
5. predicts future growth and development.

JAMES is a RESTful API that runs on a remote host. The following sections illustrate how a client can make requests to JAMES using various client languages. In principle, any `HTTP` client will work with JAMES. The document highlights some applications of the service and provides pointers to relevant background information. 

The service aids in monitoring and evaluating childhood growth. JAMES is created and maintained by the Netherlands Organisation for Applied Scientific Research TNO. Please contact Stef van Buuren <stef.vanbuuren at tno.nl> for further information.

### Primary JAMES user functionality

| Verb  | API end point              | Description                                | Maps to `james` function |
|:------|:-------------------------- |:------------------------------------------ |:-------------------------|
| POST  | `/version/{dfm}`           | Obtain version information                 | `version()`              |
| POST  | `/data/upload/{dfm}`       | Upload child data                          | `upload_data()`          |
| &nbsp;| &nbsp;                     | &nbsp;                                     | &nbsp;                   |
| POST  | `/charts/draw/{ffm}`       | Draw child data on growth chart            | `draw_chart()`           |
| POST  | `/charts/list/{dfm}`       | List available growth charts               | `list_charts()`          |
| POST  | `/charts/validate/{dfm}`   | Validate a chart code                      | `validate_chartcode()`   |
| &nbsp;| &nbsp;                     | &nbsp;                                     | &nbsp;                   |
| POST  | `/dscore/calculate/{dfm}`  | Calculate developmental score (D-score)    | `calculate_dscore()`     |
| POST  | `/ddomain/calculate/{dfm}` | Calculate domain scores                    | `calculate_ddomain()`    |
| POST  | `/vwc/select/{dfm}`        | Select developmental milestones for age    | `select_vwc()`           |
| POST  | `/vwc/percentiles/{dfm}`   | Obtain developmental milestone percentiles | `percentiles_vwc()`      |
| POST  | `/dcat/calculate/{dfm}`    | Adaptive testing of milestones             | `dcat()`                 |
| &nbsp;| &nbsp;                     | &nbsp;                                     | &nbsp;                   |
| POST  | `/screeners/list/{dfm}`    | List available growth screeners            | `list_screeners()`       |
| POST  | `/screeners/apply/{dfm}`   | Apply growth screeners to child data       | `apply_screeners()`      |
| &nbsp;| &nbsp;                     | &nbsp;                                     | &nbsp;                   |
| GET   | `/site`                    | Request empty site                         | `request_site()`         |
| POST  | `/site/request/{dfm}`      | Request personalised site                  | `request_site()`         |
| &nbsp;| &nbsp;                     | &nbsp;                                     | &nbsp;                   |
| POST  | `/blend/request/{sfm}`     | Obtain a blend from multiple end points    | `request_blend()`        |
| &nbsp;| &nbsp;                     | &nbsp;                                     | &nbsp;                   |
| GET   | `/{session}/{info}`        | Extract session details                    |                          |
| GET   | `/{2}/{1}/man`             | Consult R help                             | `help({1}_{2})`          |

The table lists the defined API end points and the mapping to each end point to the corresponding R function. 

The definition of the JAMES endpoints can be found at [OpenAPI specification](https://james.groeidiagrammen.nl/docs/).

## Resources

### Internal

| Description                                           | Status                                  |
|:------------------------------------------------------|:----------------------------------------|
| [Example requests](https://james.groeidiagrammen.nl) | current |
| [OpenAPI specification](https://james.groeidiagrammen.nl/docs/) | current     |
| [JSON data schema 3.0](https://james.groeidiagrammen.nl/schemas/bds_v3.0.json) | current |
| [JAMES issue tracker](https://github.com/growthcharts/james/issues) | current |
| [GitHub Organization](https://github.com/growthcharts) | current |

### External

| Description                                           | Status                                  |
|:------------------------------------------------------|:----------------------------------------|
| [JAMES demo](https://tnochildhealthstatistics.shinyapps.io/james_tryout/) | current |
| [Basisdataset JGZ](https://decor.nictiz.nl/pub/jeugdgezondheidszorg/jgz-html-20240426T081156/index.html) | current |
| [OpenCPU API](https://www.opencpu.org/api.html) | current |
