
# D-score for Thomas S
# g <- draw_chart(txt = "",
#                 loc = "http://localhost/ocpu/tmp/x075f3ca338513f/",
#                 chartcode = "",
#                 selector = "derive",
#                 chartgrp = "nl2010",
#                 agegrp = "0-15m",
#                 sex = "male",
#                 etn = "nl",
#                 ga = 25,
#                 side = "dsc",
#                 curve_interpolation = TRUE,
#                 quiet = FALSE,
#                 dnr = "2-4",
#                 lo = "36m",
#                 hi = "45m",
#                 nmatch = 0L,
#                 exact_sex = TRUE,
#                 exact_ga = FALSE,
#                 show_realized = FALSE,
#                 show_future = FALSE)
